baseURL: 'https://kirinthos.github.io'
languageCode: 'en-us'
title: 'Cross Compiled'
theme: "PaperMod"

params:
  disableThemeToggle: true
  showShareButtons: true
  tags: true
  showToc: true
  showPostNavLinks: true
