baseURL: 'https://crosscompiled.com'
languageCode: 'en-us'
title: 'Cross Compiled'
description: 'Writings about technical topics'
theme: "PaperMod"

params:
  disableThemeToggle: true
  showShareButtons: true
  tags: true
  showToc: true
  showPostNavLinks: true
